### PR TITLE
Compress data before sending to Kinesis.

### PR DESCRIPTION
**Pull request by akinnane**
This emulates CloudWatch Logs more closely. The `kinesis.PutRecordInput.Data` field's content is now gzipped before ingestion.

In CSLS there is logic to detect the zip / unzipped logs. I would like to remove it to simplify the parsing code. Having a mix of gzipped and plaintext records makes data analysis during a CSLS failure harder.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html
>The Data attribute in a Kinesis record is Base64 encoded and compressed with the gzip format.

https://github.com/alphagov/centralised-security-logging-service/blob/4b417ce270c66d56e33f327939eadc0841bf94ed/kinesis_processor/src/kinesis_firehose.rs#L99

### CODE REVIEW

**Review by 0atman — APPROVED** [review]
I'm not familiar with this project or environment, but FWIW tests pass.
```
SUCCESS! -- 30 Passed | 0 Failed | 0 Pending | 0 Skipped
```

**Comment by chrisfarms** [comment]
Think this project was moved: https://github.com/alphagov/paas-csls-splunk-broker

Think it needs removing from this repo!

**Comment by chrisfarms** [comment]
cc @AP-Hunt

**Comment by akinnane** [comment]
Moved to https://github.com/alphagov/paas-csls-splunk-broker/pull/9

**Pull request closed without merging**
