### PR TITLE
upgrade concourse to v6.1.0

### PR DESCRIPTION
**Pull request by chrisfarms**
## What

Upgrades concourse to v6.1.0

## Notes

https://github.com/concourse/concourse/releases/tag/v6.1.0

## Why

Staying up to date, and we want to test the pipeline

### CODE REVIEW

**Comment by Krenair** [comment]
Could jump straight to 6.2.0 now?

**Comment by Krenair** [comment]
Or 6.3.0...

**Comment by tlwr** [comment]
6.3 is fast, Lee upgraded ours today

**Comment by chrisfarms** [comment]
Closing in favour of https://github.com/alphagov/tech-ops/pull/103

**Pull request closed without merging**
